export const CALLTIPS: Record<string, string> = {
  print: 'print(*objects, sep=" ", end="\\n", file=sys.stdout, flush=False)',
  len: "len(s)",
  range: "range(stop) | range(start, stop[, step])",
  input: 'input(prompt="")',
  int: "int(x=0, base=10)",
  str: 'str(object="")',
  float: "float(x=0)",
  list: "list(iterable=())",
  dict: "dict(**kwargs)",
  set: "set(iterable=())",
  tuple: "tuple(iterable=())",
  bool: "bool(x=False)",
  type: "type(object)",
  isinstance: "isinstance(object, classinfo)",
  enumerate: "enumerate(iterable, start=0)",
  zip: "zip(*iterables)",
  map: "map(func, *iterables)",
  filter: "filter(function, iterable)",
  sorted: "sorted(iterable, key=None, reverse=False)",
  reversed: "reversed(seq)",
  sum: "sum(iterable, start=0)",
  min: "min(*args, key=None)",
  max: "max(*args, key=None)",
  abs: "abs(x)",
  round: "round(number, ndigits=None)",
  open: 'open(file, mode="r", encoding=None)',
  hasattr: "hasattr(object, name)",
  getattr: "getattr(object, name, default)",
  setattr: "setattr(object, name, value)",
  super: "super(type, obj)",
  property: "property(fget=None, fset=None, fdel=None, doc=None)",
  format: 'format(value, format_spec="")',
  vars: "vars([object])",
  dir: "dir([object])",
  repr: "repr(object)",
  id: "id(object)",
  hex: "hex(x)",
  oct: "oct(x)",
  bin: "bin(x)",
  ord: "ord(c)",
  chr: "chr(i)",
  hash: "hash(object)",
  iter: "iter(object[, sentinel])",
  next: "next(iterator[, default])",
  all: "all(iterable)",
  any: "any(iterable)",
  callable: "callable(object)",
};
