/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Script {
  'created' : Time,
  'content' : string,
  'name' : string,
  'updated' : Time,
}
export interface ScriptInput { 'content' : string }
export interface ScriptMetadata {
  'created' : Time,
  'preview' : string,
  'name' : string,
  'updated' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'clearHistory' : ActorMethod<[], undefined>,
  'deleteScript' : ActorMethod<[string], undefined>,
  'getLastCommands' : ActorMethod<[bigint], Array<[Time, string]>>,
  'getScript' : ActorMethod<[string], Script>,
  'listScripts' : ActorMethod<[], Array<ScriptMetadata>>,
  'renameScript' : ActorMethod<[string, string], undefined>,
  'saveScript' : ActorMethod<[string, ScriptInput], undefined>,
  'storeCommand' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];