/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Script = IDL.Record({
  'created' : Time,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'updated' : Time,
});
export const ScriptMetadata = IDL.Record({
  'created' : Time,
  'preview' : IDL.Text,
  'name' : IDL.Text,
  'updated' : Time,
});
export const ScriptInput = IDL.Record({ 'content' : IDL.Text });

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'deleteScript' : IDL.Func([IDL.Text], [], []),
  'getLastCommands' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(Time, IDL.Text))],
      ['query'],
    ),
  'getScript' : IDL.Func([IDL.Text], [Script], ['query']),
  'listScripts' : IDL.Func([], [IDL.Vec(ScriptMetadata)], ['query']),
  'renameScript' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveScript' : IDL.Func([IDL.Text, ScriptInput], [], []),
  'storeCommand' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Script = IDL.Record({
    'created' : Time,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'updated' : Time,
  });
  const ScriptMetadata = IDL.Record({
    'created' : Time,
    'preview' : IDL.Text,
    'name' : IDL.Text,
    'updated' : Time,
  });
  const ScriptInput = IDL.Record({ 'content' : IDL.Text });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'deleteScript' : IDL.Func([IDL.Text], [], []),
    'getLastCommands' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(Time, IDL.Text))],
        ['query'],
      ),
    'getScript' : IDL.Func([IDL.Text], [Script], ['query']),
    'listScripts' : IDL.Func([], [IDL.Vec(ScriptMetadata)], ['query']),
    'renameScript' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveScript' : IDL.Func([IDL.Text, ScriptInput], [], []),
    'storeCommand' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };